type Cliente {
  id: ID,
  nomeCompleto: String,
  email: String,
  cpf: String,
  dataNascimento: String,
}

input ClienteInput {
  nomeCompleto: String,
  email: String,
  cpf: String,
  dataNascimento: String,
}

input FiltroInput {
  id: ID,
  cpf: String,
  email: String,
}

type Query {
  cliente(id: ID!): Cliente,

  clientes: [Cliente],
}

type Mutation {
  criaCliente(data: ClienteInput): Cliente!,

  atualizaCliente(id: ID!, data: ClienteInput): Cliente!,

  deletaCliente(filtro: FiltroInput!): Boolean,
}